package com.geektext.geektext_backend_api.entity;

import jakarta.persistence.*;

@Entity
@Table(name = "comments")
public class CommentsEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "comment_id", columnDefinition = "BIGINT GENERATED BY DEFAULT AS IDENTITY")
    private Long comment_id;

    @Column(name = "comment")
    private String comment;

    @ManyToOne
    @JoinColumn(name = "user_id")
    private UserEntity user_id;

    @ManyToOne
    @JoinColumn(name = "isbn")
    private BookEntity isbn;

    public CommentsEntity(String comment, UserEntity user_id, BookEntity isbn){
        this.comment = comment;
        this.isbn = isbn;
        this.user_id = user_id;
    }

    public CommentsEntity() {}

    public Long getComment_id() {
        return comment_id;
    }

    public void setComment_id(Long comment_id) {
        this.comment_id = comment_id;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public UserEntity getUser_id() {
        return user_id;
    }

    public void setUser_id(UserEntity user_id) {
        this.user_id = user_id;
    }

    public BookEntity getIsbn() {
        return isbn;
    }

    public void setIsbn(BookEntity isbn) {
        this.isbn = isbn;
    }
}
