package com.geektext.geektext_backend_api.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;
import org.springframework.data.annotation.CreatedDate;
import java.time.LocalDateTime;

/*
This class represents the Comment entity in the system. It captures a user's comment for a particular book they have purchased.
Each comment includes the text of the comment, the user who made it, and the book it refers to.
*/
@Entity
@Table(name = "comments")
public class CommentsEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "comment_id", columnDefinition = "BIGINT GENERATED BY DEFAULT AS IDENTITY")
    private Long commentId;

    @CreatedDate
    @Column(name = "datestamp")
    private LocalDateTime datestamp;

    @Column(name = "comment")
    private String comment;

    @JsonIgnore
    @ManyToOne
    @JoinColumn(name = "user_id")
    private UserEntity user;

    @JsonIgnore
    @ManyToOne
    @JoinColumn(name = "isbn")
    private BookEntity book;

    public CommentsEntity(String comment, UserEntity user, BookEntity book) {
        this.comment = comment;
        this.book = book;
        this.user = user;
        //this.datestamp = datestamp;
    }

    public CommentsEntity() {
    }

    public Long getCommentId() {
        return commentId;
    }

    public void setCommentId(Long commentId) {
        this.commentId = commentId;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public UserEntity getUser() {
        return user;
    }

    public void setUser(UserEntity user) {
        this.user = user;
    }

    public BookEntity getBook() {
        return book;
    }

    public void setBook(BookEntity book) {
        this.book = book;
    }

}