package com.geektext.geektext_backend_api.entity;

import jakarta.persistence.*;

@Entity
@Table(name = "comments")
public class CommentsEntity {


    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "comment_id", columnDefinition = "BIGINT GENERATED BY DEFAULT AS IDENTITY")
    private Long comment_id;


    @Column(name = "comment")
    private String comment;


    @Column(name = "user_id")
    private int user_id;


    @Column(name = "isbn")
    private String isbn;




    public CommentsEntity(Long comment_id, String comment, int user_id, String isbn){
        this.comment = comment;
        this.comment_id = comment_id;
        this.isbn = isbn;
        this. user_id = user_id;
    }


    public int getUser_id() {
        return user_id;
    }


    public void setUser_id(int user_id) {
        this.user_id = user_id;
    }


    public Long getComment_id() {
        return comment_id;
    }


    public void setComment(String comment) {
        this.comment = comment;
    }


    public String getIsbn() {
        return isbn;
    }


    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }


    public void setComment_id(Long comment_id) {
        this.comment_id = comment_id;
    }


    public String getComment() {
        return comment;
    }


}
