package com.geektext.geektext_backend_api.entity;

import java.util.List;

import jakarta.persistence.*;

@Entity
@Table(name = "publishers")

public class PublisherEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "publisher_id", columnDefinition = "BIGINT GENERATED BY DEFAULT AS IDENTITY")
    private int id;

    @Column(name = "publisher_name")
    private String publisher_name;

    @OneToMany(mappedBy = "publisher", cascade = CascadeType.ALL)
    private List<BookEntity> books;


    public PublisherEntity() {}

    public PublisherEntity(String publisher_name){
        this.publisher_name = publisher_name;
    }


    public int getPublisher_id() {
        return id;
    }

    public void setPublisher_id(int publisher_id) {
        this.id = publisher_id;
    }

    public String getPublisher_name() {
        return publisher_name;
    }

    public void setPublisher_name(String publisher_name) {
        this.publisher_name = publisher_name;
    }
}
